version: "3.9"
networks: { proyecto: { driver: bridge } }
volumes: { influx-data: {}, grafana-data: {} }

services:
  influxdb:
    image: influxdb:2.7
    ports: ["8086:8086"]
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=wsn
      - DOCKER_INFLUXDB_INIT_BUCKET=temperatures
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
    volumes: [ "influx-data:/var/lib/influxdb2" ]
    networks: [ proyecto ]

  grafana:
    image: grafana/grafana:11.1.0
    ports: ["3000:3000"]
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes: [ "grafana-data:/var/lib/grafana" ]
    networks: [ proyecto ]
